channels:
  - conda-forge
dependencies:
  - python
  - future
  - numpy
  - scipy
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - pyfftw
  - scikit-video
  - ffmpeg
  - pip:
    - git+https://github.com/bwohlberg/sporco.git@v0.2.1
